### ISSUE TITLE
Game lost at start?

### ISSUE THREAD

**Issue by adriweb** [commandblockguy/mahjong-ce#1]
Apparently it's possible that upon starting a new game, the initial random combination isn't solvable, and the game says that we've lost :P
Could you check if a move has been made prior to display the message, and if not, re-start/shuffle/initialize the board until a solvable one has been found? (or at least where it's not initially lost)

(initially found by @critor)

**Comment by commandz0** [comment]
Fixed. Will get an update out soon.
Currently it retries up to ten times to generate a map until it has possible moves. If it fails all ten times it displays an error. I may implement something to make sure it's solvable in the future.
